### ISSUE TITLE
Multiple Ph.D. positions in Oregon State University

### ISSUE THREAD

**Issue by wdong5** [phdoffer/phdoffer_questions#1]
Advisor: Wenqian Dong (joining Oregon state university in Fall 2024);
Website: https://wdong5.github.io/
Topics: High-performance Computing, AI for Science, and MLsys;

**Comment by duooffer** [comment]
> Advisor: Wenqian Dong (joining Oregon state university in Fall 2024); Website: https://wdong5.github.io/ Topics: High-performance Computing, AI for Science, and MLsys;

Please add your ad via this link:  https://forms.gle/9ETnp3CSFNedaEoaA
